// Generated by scripts/generate-appearance.py. Do not edit directly.
pragma Singleton

import QtQuick

QtObject {
    readonly property color background: "#08090b"
    readonly property color surface: "#0a0c0f"
    readonly property color surfaceRaised: "#0f1115"
    readonly property color surfaceHover: "#161922"
    readonly property color foreground: "#f1f1f4"
    readonly property color muted: "#92959f"
    readonly property color dim: "#666a74"
    readonly property color accent: "#9892e8"
    readonly property color cyan: "#67b8c9"
    readonly property color amber: "#c49b63"
    readonly property color warning: "#c8a367"
    readonly property color danger: "#c46f7d"
    readonly property color success: "#7fa98a"

    readonly property string fontFamily: "JetBrainsMono Nerd Font"
    readonly property int railHeight: 64
    readonly property int islandHeight: 56
    readonly property int screenInset: 20
    readonly property int islandGap: 22
    readonly property int compactCorner: 16
    readonly property int touchTarget: 48
    readonly property int popupOpenMs: 140
    readonly property int popupCloseMs: 110
}
