[Theme]
Current=senomyos
ThemeDir=/usr/share/sddm/themes
EnableAvatars=false
Font=JetBrainsMono Nerd Font

[Users]
RememberLastUser=true
RememberLastSession=true

[Autologin]
User=
Session=
Relogin=false

[Wayland]
SessionCommand=/usr/local/libexec/senomy-sddm-wayland-session

[X11]
SessionCommand=/usr/local/libexec/senomy-sddm-x11-session
