#!/usr/bin/env python3
"""Generate toolkit-specific color contracts from appearance/tokens.json."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys

from frame_geometry import corner_geometry, crest_geometry, edge_geometry, motif_geometry


ROOT = Path(__file__).resolve().parent.parent
TOKENS_PATH = ROOT / "appearance" / "tokens.json"
FRAME_MANIFEST_PATH = ROOT / "appearance" / "shared" / "frames" / "frame-system.json"


def rgb(value: str) -> tuple[int, int, int]:
    if len(value) != 7 or not value.startswith("#"):
        raise ValueError(f"expected #rrggbb color, got {value!r}")
    return tuple(int(value[offset : offset + 2], 16) for offset in (1, 3, 5))


def rgba(value: str, alpha: float) -> str:
    red, green, blue = rgb(value)
    return f"rgba({red}, {green}, {blue}, {alpha:.2f})"


def rgba_percent(value: str, alpha: float) -> str:
    red, green, blue = rgb(value)
    return f"rgba({red}, {green}, {blue}, {round(alpha * 100)}%)"


def render_scss(tokens: dict, frame_manifest: dict) -> str:
    colors = tokens["colors"]
    typography = tokens["typography"]
    geometry = tokens["geometry"]
    density = tokens["density"]
    palettes = tokens["palettes"]
    frame = tokens["frame_system"]
    frame_colors = frame["colors"]
    frame_glass = frame["glass"]
    frame_tiers = frame_manifest["tiers"]
    compact_frame = frame_tiers["compact"]
    frame_tier_lines: list[str] = []
    for tier_name in ("compact", "standard", "large"):
        tier = frame_tiers[tier_name]
        frame_tier_lines.extend(
            (
                f"$senomy-frame-{tier_name}-corner-width: {tier['corner']['width']}px;",
                f"$senomy-frame-{tier_name}-corner-height: {tier['corner']['height']}px;",
                f"$senomy-frame-{tier_name}-edge-horizontal-height: {tier['edge']['horizontal']['height']}px;",
                f"$senomy-frame-{tier_name}-edge-vertical-width: {tier['edge']['vertical']['width']}px;",
                f"$senomy-frame-{tier_name}-safe-top: {tier['content_safe']['top']}px;",
                f"$senomy-frame-{tier_name}-safe-right: {tier['content_safe']['right']}px;",
                f"$senomy-frame-{tier_name}-safe-bottom: {tier['content_safe']['bottom']}px;",
                f"$senomy-frame-{tier_name}-safe-left: {tier['content_safe']['left']}px;",
            )
        )
    frame_tier_contract = "\n".join(frame_tier_lines)
    palette_lines: list[str] = []
    for name in ("cyan", "violet", "amber"):
        palette = palettes[name]
        palette_lines.extend(
            (
                f"$senomy-{name}-accent: {palette['accent']};",
                f"$senomy-{name}-bright: {palette['bright']};",
                f"$senomy-{name}-soft: {rgba(palette['accent'], palette['soft_alpha'])};",
                f"$senomy-{name}-medium: {rgba(palette['accent'], palette['medium_alpha'])};",
                f"$senomy-{name}-strong: {rgba(palette['accent'], palette['strong_alpha'])};",
            )
        )
    palette_contract = "\n".join(palette_lines)
    return f"""// Generated by scripts/generate-appearance.py. Do not edit directly.
$senomy-background: {colors['background']};
$senomy-surface: {colors['surface']};
$senomy-surface-raised: {colors['surface_raised']};
$senomy-foreground: {colors['foreground']};
$senomy-muted: {colors['muted']};
$senomy-dim: {colors['dim']};
$senomy-accent: {colors['accent']};
$senomy-success: {colors['success']};
$senomy-warning: {colors['warning']};
$senomy-danger: {colors['danger']};
$senomy-border: {rgba(colors['border'], colors['border_alpha'])};
$senomy-border-strong: {rgba(colors['border'], colors['border_strong_alpha'])};
$senomy-accent-surface: {rgba(colors['accent'], colors['accent_surface_alpha'])};
$senomy-font: \"{typography['family']}\";
$senomy-font-fallback: \"{typography['fallback']}\";
$senomy-base-px: {typography['base_px']}px;
$senomy-metadata-px: {typography['metadata_px']}px;
$senomy-radius: {geometry['radius_px']}px;
$senomy-border-width: {geometry['border_px']}px;
$senomy-compact-row: {density['compact_row_px']}px;
$senomy-standard-row: {density['standard_row_px']}px;
$senomy-touch-row: {density['touch_row_px']}px;
$senomy-frame-ivory: {frame_colors['ivory']};
$senomy-frame-cold-silver: {frame_colors['cold_silver']};
$senomy-frame-steel: {frame_colors['steel']};
$senomy-frame-structural: {frame_colors['structural']};
$senomy-frame-violet: {frame_colors['violet']};
$senomy-frame-violet-light: {frame_colors['violet_light']};
$senomy-frame-glass-surface: {rgba(colors['surface'], frame_glass['surface_alpha'])};
$senomy-frame-glass-raised: {rgba(colors['surface_raised'], frame_glass['raised_alpha'])};
$senomy-frame-glass-hover: {rgba(frame_colors['ivory'], frame_glass['hover_alpha'])};
$senomy-frame-glass-focus: {rgba(frame_colors['violet'], frame_glass['focus_alpha'])};
{frame_tier_contract}
$senomy-frame-workspace-bay-label-min: {compact_frame['workspace_bay']['minimum_label_width']}px;
$senomy-frame-workspace-bay-padding: {compact_frame['workspace_bay']['horizontal_padding']}px;
{palette_contract}
"""


def render_rofi(tokens: dict) -> str:
    colors = tokens["colors"]
    frame_colors = tokens["frame_system"]["colors"]
    frame_glass = tokens["frame_system"]["glass"]
    return f"""/* Generated by scripts/generate-appearance.py. Do not edit directly. */
* {{
    background-base: {rgba_percent(colors['background'], 0.86)};
    surface: {rgba_percent(colors['surface'], 0.78)};
    surface-raised: {rgba_percent(colors['surface_raised'], 0.88)};
    surface-selected: {rgba_percent(colors['accent'], colors['accent_surface_alpha'])};
    border-soft: {rgba_percent(colors['border'], colors['border_alpha'])};
    border-muted: {rgba_percent(colors['border'], 0.10)};
    text-primary: {rgba_percent(colors['foreground'], 1.0)};
    text-muted: {rgba_percent(colors['muted'], 1.0)};
    text-dim: {rgba_percent(colors['dim'], 1.0)};
    accent: {rgba_percent(colors['accent'], 1.0)};
    success: {rgba_percent(colors['success'], 1.0)};
    warning: {rgba_percent(colors['warning'], 1.0)};
    danger: {rgba_percent(colors['danger'], 1.0)};
    frame-ivory: {rgba_percent(frame_colors['ivory'], 0.96)};
    frame-silver: {rgba_percent(frame_colors['cold_silver'], 0.86)};
    frame-steel: {rgba_percent(frame_colors['steel'], 0.82)};
    frame-structural: {rgba_percent(frame_colors['structural'], 0.90)};
    frame-violet: {rgba_percent(frame_colors['violet'], 0.94)};
    frame-violet-light: {rgba_percent(frame_colors['violet_light'], 0.94)};
    frame-glass: {rgba_percent(colors['surface'], frame_glass['raised_alpha'])};
    frame-glass-hover: {rgba_percent(frame_colors['ivory'], frame_glass['hover_alpha'])};
    frame-glass-focus: {rgba_percent(frame_colors['violet'], frame_glass['focus_alpha'])};
}}
"""


def render_gtk(tokens: dict) -> str:
    colors = tokens["colors"]
    frame_colors = tokens["frame_system"]["colors"]
    frame_glass = tokens["frame_system"]["glass"]
    return f"""/* Generated by scripts/generate-appearance.py. Do not edit directly. */
@define-color senomy_bg {colors['background']};
@define-color senomy_surface {colors['surface']};
@define-color senomy_surface_raised {colors['surface_raised']};
@define-color senomy_fg {colors['foreground']};
@define-color senomy_muted {colors['muted']};
@define-color senomy_dim {colors['dim']};
@define-color senomy_border {rgba(colors['border'], colors['border_alpha'])};
@define-color senomy_border_strong {rgba(colors['border'], colors['border_strong_alpha'])};
@define-color senomy_accent {colors['accent']};
@define-color senomy_accent_surface {rgba(colors['accent'], colors['accent_surface_alpha'])};
@define-color senomy_success {colors['success']};
@define-color senomy_warning {colors['warning']};
@define-color senomy_danger {colors['danger']};
@define-color senomy_frame_ivory {frame_colors['ivory']};
@define-color senomy_frame_silver {frame_colors['cold_silver']};
@define-color senomy_frame_steel {frame_colors['steel']};
@define-color senomy_frame_structural {frame_colors['structural']};
@define-color senomy_frame_violet {frame_colors['violet']};
@define-color senomy_frame_violet_light {frame_colors['violet_light']};
@define-color senomy_glass_surface {rgba(colors['surface'], frame_glass['raised_alpha'])};
@define-color senomy_glass_hover {rgba(frame_colors['ivory'], frame_glass['hover_alpha'])};
@define-color senomy_glass_focus {rgba(frame_colors['violet'], frame_glass['focus_alpha'])};
"""


def render_qml_js(tokens: dict) -> str:
    colors = tokens["colors"]
    typography = tokens["typography"]
    geometry = tokens["geometry"]
    return f"""// Generated by scripts/generate-appearance.py. Do not edit directly.
.pragma library

var background = \"{colors['background']}\";
var surface = \"{colors['surface']}\";
var surfaceRaised = \"{colors['surface_raised']}\";
var foreground = \"{colors['foreground']}\";
var muted = \"{colors['muted']}\";
var dim = \"{colors['dim']}\";
var accent = \"{colors['accent']}\";
var success = \"{colors['success']}\";
var warning = \"{colors['warning']}\";
var danger = \"{colors['danger']}\";
var fontFamily = \"{typography['family']}\";
var radius = {geometry['radius_px']};
"""


def render_hyprlock(template: str, tokens: dict) -> str:
    colors = tokens["colors"]
    replacements = {
        "@BACKGROUND@": rgba(colors["background"], 1.0),
        "@SURFACE@": rgba(colors["surface"], 0.98),
        "@SURFACE_RAISED@": rgba(colors["surface_raised"], 1.0),
        "@FOREGROUND@": rgba(colors["foreground"], 1.0),
        "@MUTED@": rgba(colors["muted"], 1.0),
        "@DIM@": rgba(colors["dim"], 1.0),
        "@ACCENT@": rgba(colors["accent"], 1.0),
        "@WARNING@": rgba(colors["warning"], 1.0),
        "@DANGER@": rgba(colors["danger"], 1.0),
        "@FONT@": tokens["typography"]["family"],
        "@RADIUS@": str(tokens["geometry"]["radius_px"]),
    }
    rendered = template
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    if "@" in "".join(line.split("#", 1)[0] for line in rendered.splitlines()):
        raise ValueError("unresolved placeholder in hyprlock template")
    return "# Generated by scripts/generate-appearance.py. Do not edit directly.\n" + rendered


def render_wallpaper_svg(template: str, tokens: dict) -> str:
    colors = tokens["colors"]
    replacements = {
        "@BACKGROUND@": colors["background"],
        "@SURFACE@": colors["surface"],
        "@ACCENT@": colors["accent"],
        "@CYAN@": tokens["palettes"]["cyan"]["accent"],
        "@MUTED@": colors["muted"],
    }
    rendered = template
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    if "@" in rendered:
        raise ValueError("unresolved placeholder in wallpaper template")
    return "<!-- Generated by scripts/generate-appearance.py. Do not edit directly. -->\n" + rendered


def render_brand_mark_svg(template: str, tokens: dict) -> str:
    replacements = {
        "@FOREGROUND@": tokens["colors"]["foreground"],
    }
    rendered = template
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    if "@" in rendered:
        raise ValueError("unresolved placeholder in brand mark template")
    return "<!-- Generated by scripts/generate-appearance.py. Do not edit directly. -->\n" + rendered


def render_file_folder_svg(template: str, tokens: dict) -> str:
    """Project the quiet file-workspace folder from shared frame colours."""
    colors = tokens["frame_system"]["colors"]
    replacements = {
        "@IVORY@": colors["ivory"],
        "@COLD_SILVER@": colors["cold_silver"],
        "@STEEL@": colors["steel"],
        "@STRUCTURAL@": colors["structural"],
        "@VIOLET@": colors["violet"],
    }
    rendered = template
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    if "@" in rendered:
        raise ValueError("unresolved placeholder in file-workspace folder icon")
    return "<!-- Generated by scripts/generate-appearance.py. Do not edit directly. -->\n" + rendered


def render_frame_module_svg(
    template: str,
    tokens: dict,
    *,
    width: int,
    height: int,
    title: str,
    asset_id: str,
    geometry: str,
    preserve_aspect_ratio: str,
) -> str:
    """Project one fixed or deliberately stretchable standalone SVG module."""
    colors = tokens["frame_system"]["colors"]
    replacements = {
        "@WIDTH@": str(width),
        "@HEIGHT@": str(height),
        "@TITLE@": title,
        "@ASSET_ID@": asset_id,
        "@GEOMETRY@": geometry,
        "@PRESERVE_ASPECT_RATIO@": preserve_aspect_ratio,
        "@IVORY@": colors["ivory"],
        "@COLD_SILVER@": colors["cold_silver"],
        "@STEEL@": colors["steel"],
        "@STRUCTURAL@": colors["structural"],
        "@VIOLET@": colors["violet"],
        "@VIOLET_LIGHT@": colors["violet_light"],
    }
    rendered = template
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    if "@" in rendered:
        raise ValueError(f"unresolved placeholder in frame asset {asset_id}")
    return "<!-- Generated by scripts/generate-appearance.py. Do not edit directly. -->\n" + rendered


def outputs(tokens: dict) -> dict[Path, str]:
    shell_source_path = ROOT / "appearance" / "shell" / "eww.scss"
    shell_source = shell_source_path.read_text(encoding="utf-8")
    shell_import = '@import "tokens";'
    if shell_import not in shell_source:
        raise ValueError(f"missing token import in {shell_source_path}")
    shell_tokens = render_scss(tokens, json.loads(FRAME_MANIFEST_PATH.read_text(encoding="utf-8")))
    runtime_shell = shell_source.replace(shell_import, shell_tokens, 1)
    lock_template_path = ROOT / "appearance" / "lock" / "hyprlock.conf.in"
    wallpaper_template_path = ROOT / "appearance" / "shared" / "backgrounds" / "desktop.svg.in"
    brand_mark_template_path = ROOT / "appearance" / "shared" / "brand" / "senomyos-mark.svg.in"
    file_folder_template_path = (
        ROOT
        / "appearance"
        / "file-manager"
        / "icons"
        / "SenomyOS-Files"
        / "folder.svg.in"
    )
    brand_mark_svg = render_brand_mark_svg(
        brand_mark_template_path.read_text(encoding="utf-8"), tokens
    )
    file_folder_svg = render_file_folder_svg(
        file_folder_template_path.read_text(encoding="utf-8"), tokens
    )
    frame_manifest = json.loads(FRAME_MANIFEST_PATH.read_text(encoding="utf-8"))
    frame_template = (
        ROOT / "appearance" / "shared" / "frames" / "templates" / "senomy-frame-module.svg.in"
    ).read_text(encoding="utf-8")
    generated = {
        # Eww 0.5 does not expand a nested SCSS import reliably at runtime.
        # Keep appearance/shell as the editable source, but project one
        # self-contained compatibility entry point for the live daemon.
        ROOT / "eww.scss": runtime_shell,
        ROOT / "appearance" / "shell" / "_tokens.scss": shell_tokens,
        ROOT / "appearance" / "launcher" / "rofi" / "themes" / "senomy-tokens.rasi": render_rofi(tokens),
        ROOT / "appearance" / "file-manager" / "gtk3" / "SenomyOS" / "gtk-3.0" / "senomy-tokens.css": render_gtk(tokens),
        ROOT / "appearance" / "login" / "sddm" / "senomyos" / "Theme.js": render_qml_js(tokens),
        ROOT / "appearance" / "lock" / "hyprlock.conf": render_hyprlock(
            lock_template_path.read_text(encoding="utf-8"), tokens
        ),
        ROOT / "appearance" / "shared" / "backgrounds" / "desktop.svg": render_wallpaper_svg(
            wallpaper_template_path.read_text(encoding="utf-8"), tokens
        ),
        ROOT / "appearance" / "shared" / "brand" / "senomyos-mark.svg": brand_mark_svg,
        # Keep the boot projection as a regular file: both transactional
        # deployers deliberately reject symlink sources.
        ROOT / "appearance" / "boot" / "assets" / "senomyos-mark.svg": brand_mark_svg,
    }
    frame_root = ROOT / frame_manifest["asset_root"]
    for tier, spec in frame_manifest["tiers"].items():
        corner_width = spec["corner"]["width"]
        corner_height = spec["corner"]["height"]
        for corner in ("tl", "tr", "bl", "br"):
            asset_id = f"frame-{tier}-corner-{corner}"
            generated[frame_root / tier / f"corner-{corner}.svg"] = render_frame_module_svg(
                frame_template,
                tokens,
                width=corner_width,
                height=corner_height,
                title=f"SenomyOS {tier} frame corner {corner.upper()}",
                asset_id=asset_id,
                geometry=corner_geometry(tier, corner, corner_width, corner_height),
                preserve_aspect_ratio="xMidYMid meet",
            )

        horizontal = spec["edge"]["horizontal"]
        vertical = spec["edge"]["vertical"]
        for edge in ("top", "bottom"):
            asset_id = f"frame-{tier}-edge-{edge}"
            generated[frame_root / tier / f"edge-{edge}.svg"] = render_frame_module_svg(
                frame_template,
                tokens,
                width=horizontal["width"],
                height=horizontal["height"],
                title=f"SenomyOS {tier} neutral {edge} edge",
                asset_id=asset_id,
                geometry=edge_geometry(edge, horizontal["width"], horizontal["height"]),
                preserve_aspect_ratio="none",
            )
        for edge in ("left", "right"):
            asset_id = f"frame-{tier}-edge-{edge}"
            generated[frame_root / tier / f"edge-{edge}.svg"] = render_frame_module_svg(
                frame_template,
                tokens,
                width=vertical["width"],
                height=vertical["height"],
                title=f"SenomyOS {tier} neutral {edge} edge",
                asset_id=asset_id,
                geometry=edge_geometry(edge, vertical["width"], vertical["height"]),
                preserve_aspect_ratio="none",
            )

    for name, spec in frame_manifest["motifs"].items():
        generated[frame_root / "motifs" / f"{name}.svg"] = render_frame_module_svg(
            frame_template,
            tokens,
            width=spec["width"],
            height=spec["height"],
            title=f"SenomyOS {name} frame motif",
            asset_id=f"frame-motif-{name}",
            geometry=motif_geometry(name),
            preserve_aspect_ratio="xMidYMid meet",
        )

    for name, spec in frame_manifest["crests"].items():
        generated[frame_root / "crests" / f"{name}.svg"] = render_frame_module_svg(
            frame_template,
            tokens,
            width=spec["width"],
            height=spec["height"],
            title=f"SenomyOS {name} frame crest",
            asset_id=f"frame-crest-{name}",
            geometry=crest_geometry(name),
            preserve_aspect_ratio="xMidYMid meet",
        )

    # Rofi and GTK themes are deployed outside the repository. Project the
    # exact canonical modules beside each theme so all runtime URLs remain
    # relative, portable, and independent of this checkout path.
    rofi_asset_root = ROOT / "appearance" / "launcher" / "rofi" / "assets"
    for name in ("corner-tl", "corner-tr", "corner-bl", "corner-br"):
        generated[rofi_asset_root / f"frame-standard-{name}.svg"] = generated[
            frame_root / "standard" / f"{name}.svg"
        ]
    generated[rofi_asset_root / "frame-crest-medium.svg"] = generated[
        frame_root / "crests" / "medium.svg"
    ]
    generated[rofi_asset_root / "frame-motif-diagnostic-tick.svg"] = generated[
        frame_root / "motifs" / "diagnostic-tick.svg"
    ]

    gtk_asset_root = (
        ROOT / "appearance" / "file-manager" / "gtk3" / "SenomyOS" / "gtk-3.0" / "assets"
    )
    for corner in ("tl", "tr", "bl", "br"):
        generated[gtk_asset_root / f"frame-window-corner-{corner}.svg"] = render_frame_module_svg(
            frame_template,
            tokens,
            width=20,
            height=20,
            title=f"SenomyOS compositor-aligned window corner {corner.upper()}",
            asset_id=f"frame-window-corner-{corner}",
            geometry=corner_geometry("window", corner, 20, 20),
            preserve_aspect_ratio="xMidYMid meet",
        )
    for edge in ("top", "bottom", "left", "right"):
        generated[gtk_asset_root / f"frame-window-edge-{edge}.svg"] = generated[
            frame_root / "compact" / f"edge-{edge}.svg"
        ]
    for name in (
        "corner-tl",
        "corner-tr",
        "corner-bl",
        "corner-br",
        "edge-top",
        "edge-bottom",
        "edge-left",
        "edge-right",
    ):
        generated[gtk_asset_root / f"frame-large-{name}.svg"] = generated[
            frame_root / "large" / f"{name}.svg"
        ]
    generated[gtk_asset_root / "frame-crest-wide.svg"] = generated[
        frame_root / "crests" / "wide.svg"
    ]
    generated[gtk_asset_root / "frame-motif-diagnostic-tick.svg"] = generated[
        frame_root / "motifs" / "diagnostic-tick.svg"
    ]

    # The scoped file-workspace icon theme inherits every non-folder icon from
    # the desktop theme. These aliases deliberately replace only folder marks,
    # keeping MIME/application identity colours intact while removing the
    # dominant bright-blue folder field from Thunar.
    file_icon_root = (
        ROOT
        / "appearance"
        / "file-manager"
        / "icons"
        / "SenomyOS-Files"
        / "scalable"
        / "places"
    )
    for name in (
        "folder",
        "folder-drag-accept",
        "folder-documents",
        "folder-download",
        "folder-music",
        "folder-network",
        "folder-open",
        "folder-pictures",
        "folder-publicshare",
        "folder-remote",
        "folder-saved-search",
        "folder-templates",
        "folder-videos",
        "folder-visiting",
    ):
        generated[file_icon_root / f"{name}.svg"] = file_folder_svg

    # SDDM is installed as a self-contained theme under /usr/share. Project the
    # same Compact modules used by the live Rail into the theme so relative
    # paths remain valid both in test mode and at the real greeter.
    sddm_frame_root = (
        ROOT / "appearance" / "login" / "sddm" / "senomyos" / "assets" / "frames"
    )
    for name in (
        "corner-tl",
        "corner-tr",
        "corner-bl",
        "corner-br",
        "edge-top",
        "edge-bottom",
        "edge-left",
        "edge-right",
    ):
        generated[sddm_frame_root / "compact" / f"{name}.svg"] = generated[
            frame_root / "compact" / f"{name}.svg"
        ]
    for name in (
        "controls",
        "identity",
        "junction",
        "diagnostic-tick",
        "clock-notification",
    ):
        generated[sddm_frame_root / "motifs" / f"{name}.svg"] = generated[
            frame_root / "motifs" / f"{name}.svg"
        ]
    return generated

def render_svg_png(path: Path) -> bytes:
    try:
        return subprocess.run(
            ("rsvg-convert", "--width", "64", "--height", "64", str(path)),
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ).stdout
    except FileNotFoundError as error:
        raise RuntimeError("rsvg-convert is required to build Hyprlock PNG icons") from error


def render_svg_text_png(svg: str, width: int, height: int) -> bytes:
    try:
        return subprocess.run(
            ("rsvg-convert", "--width", str(width), "--height", str(height)),
            input=svg.encode("utf-8"),
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ).stdout
    except FileNotFoundError as error:
        raise RuntimeError("rsvg-convert is required to build SVG raster projections") from error


def render_wallpaper_png(source: Path) -> bytes:
    environment = os.environ.copy()
    environment["SOURCE_DATE_EPOCH"] = "0"
    try:
        return subprocess.run(
            (
                "magick", str(source), "-auto-orient",
                "-resize", "1920x1080^", "-gravity", "center",
                "-extent", "1920x1080", "-strip",
                "-define", "png:exclude-chunks=date,time", "png:-",
            ),
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=environment,
        ).stdout
    except FileNotFoundError as error:
        raise RuntimeError("ImageMagick is required to build the desktop wallpaper") from error


def blur_wallpaper(png: bytes) -> bytes:
    environment = os.environ.copy()
    environment["SOURCE_DATE_EPOCH"] = "0"
    try:
        return subprocess.run(
            (
                "magick", "png:-", "-strip", "-blur", "0x22",
                "-brightness-contrast", "6x-2",
                "-define", "png:exclude-chunks=date,time", "png:-",
            ),
            input=png,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=environment,
        ).stdout
    except FileNotFoundError as error:
        raise RuntimeError("ImageMagick is required to build the blurred login wallpaper") from error


def render_lock_frame_png(
    tokens: dict,
    frame_root: Path,
    *,
    width: int,
    height: int,
    motif: str,
    motif_anchor: str,
) -> bytes:
    """Compose one exact Hyprlock frame from the live Rail's fixed modules."""
    compact = {
        "corner": (16, 16),
        "horizontal_edge_height": 6,
        "vertical_edge_width": 6,
    }
    motif_sizes = {
        "controls": (10, 6),
        "identity": (24, 10),
        "junction": (6, 6),
        "diagnostic-tick": (28, 8),
        "clock-notification": (10, 6),
    }
    corner_width, corner_height = compact["corner"]
    edge_height = compact["horizontal_edge_height"]
    edge_width = compact["vertical_edge_width"]
    motif_width, motif_height = motif_sizes[motif]
    motif_y = 0 if motif_anchor == "top" else height - motif_height

    surface_red, surface_green, surface_blue = rgb(tokens["colors"]["surface_raised"])
    background_red, background_green, background_blue = rgb(tokens["colors"]["background"])
    gradient = (
        f"gradient:rgba({surface_red},{surface_green},{surface_blue},0.72)-"
        f"rgba({background_red},{background_green},{background_blue},0.52)"
    )
    placements = (
        (frame_root / "compact" / "corner-tl.svg", corner_width, corner_height, 0, 0),
        (frame_root / "compact" / "corner-tr.svg", corner_width, corner_height, width - corner_width, 0),
        (frame_root / "compact" / "corner-bl.svg", corner_width, corner_height, 0, height - corner_height),
        (frame_root / "compact" / "corner-br.svg", corner_width, corner_height, width - corner_width, height - corner_height),
        (frame_root / "compact" / "edge-top.svg", width - (corner_width * 2), edge_height, corner_width, 0),
        (frame_root / "compact" / "edge-bottom.svg", width - (corner_width * 2), edge_height, corner_width, height - edge_height),
        (frame_root / "compact" / "edge-left.svg", edge_width, height - (corner_height * 2), 0, corner_height),
        (frame_root / "compact" / "edge-right.svg", edge_width, height - (corner_height * 2), width - edge_width, corner_height),
        (frame_root / "motifs" / f"{motif}.svg", motif_width, motif_height, (width - motif_width) // 2, motif_y),
    )

    command = [
        "magick",
        "(",
        "-size", f"{width}x{height}",
        "-define", "gradient:angle=105",
        gradient,
        ")",
        "(",
        "-size", f"{width}x{height}",
        "xc:none",
        "-fill", "white",
        "-draw", f"roundrectangle 0,0,{width - 1},{height - 1},16,16",
        ")",
        "-alpha", "off",
        "-compose", "CopyOpacity",
        "-composite",
    ]
    for source, item_width, item_height, x, y in placements:
        command.extend(
            (
                "(", str(source), "-background", "none",
                "-resize", f"{item_width}x{item_height}!", ")",
                "-compose", "over", "-geometry", f"+{x}+{y}", "-composite",
            )
        )
    command.extend(("-strip", "-define", "png:exclude-chunks=date,time", "png:-"))

    environment = os.environ.copy()
    environment["SOURCE_DATE_EPOCH"] = "0"
    try:
        return subprocess.run(
            command,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=environment,
        ).stdout
    except FileNotFoundError as error:
        raise RuntimeError("ImageMagick is required to build Hyprlock frame projections") from error


def binary_outputs(tokens: dict) -> dict[Path, bytes]:
    shared = ROOT / "appearance" / "shared"
    wallpaper_png = render_wallpaper_png(
        shared / "backgrounds" / "cathedral-reliquary-v1.png"
    )
    wallpaper_blurred = blur_wallpaper(wallpaper_png)
    brand_mark_svg = render_brand_mark_svg(
        (ROOT / "appearance" / "shared" / "brand" / "senomyos-mark.svg.in").read_text(encoding="utf-8"),
        tokens,
    )
    brand_mark_64 = render_svg_text_png(brand_mark_svg, 64, 64)
    brand_mark_128 = render_svg_text_png(brand_mark_svg, 128, 128)
    brand_mark_256 = render_svg_text_png(brand_mark_svg, 256, 256)
    outputs = {
        shared / "backgrounds" / "desktop.png": wallpaper_png,
        shared / "backgrounds" / "desktop-blurred.png": wallpaper_blurred,
        ROOT / "appearance" / "login" / "sddm" / "senomyos" / "assets" / "background.png": wallpaper_blurred,
        ROOT / "appearance" / "login" / "sddm" / "senomyos" / "assets" / "avatar.png": (
            shared / "avatar.png"
        ).read_bytes(),
        ROOT / "appearance" / "shared" / "brand" / "senomyos-mark-64.png": brand_mark_64,
        ROOT / "appearance" / "shared" / "brand" / "senomyos-mark-128.png": brand_mark_128,
        ROOT / "appearance" / "shared" / "brand" / "senomyos-mark-256.png": brand_mark_256,
        # Compatibility projection retained for the existing GRUB/Plymouth
        # manifests and their already-issued rollback receipts.
        ROOT / "appearance" / "boot" / "assets" / "senomyos-mark.png": brand_mark_256,
    }
    sddm_icons = ROOT / "appearance" / "login" / "sddm" / "senomyos" / "assets" / "icons"
    lock_icons = ROOT / "appearance" / "lock" / "assets" / "icons"
    for name in ("accessibility", "keyboard", "next", "power", "recovery", "restart", "session"):
        outputs[lock_icons / f"{name}.png"] = render_svg_png(sddm_icons / f"{name}.svg")
    lock_frames = ROOT / "appearance" / "lock" / "assets" / "frames"
    frame_root = ROOT / "appearance" / "shared" / "frames" / "generated"
    for name, width, motif, motif_anchor in (
        ("utility", 408, "controls", "top"),
        ("identity", 284, "identity", "top"),
        ("authentication", 654, "junction", "top"),
        ("session", 202, "diagnostic-tick", "bottom"),
        ("clock", 220, "clock-notification", "bottom"),
    ):
        outputs[lock_frames / f"{name}.png"] = render_lock_frame_png(
            tokens,
            frame_root,
            width=width,
            height=170,
            motif=motif,
            motif_anchor=motif_anchor,
        )
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", nargs="?", choices=("build", "check"), default="build")
    args = parser.parse_args()

    tokens = json.loads(TOKENS_PATH.read_text(encoding="utf-8"))
    stale: list[str] = []
    for path, expected in outputs(tokens).items():
        if args.mode == "check":
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(f".{path.name}.new")
        temporary.write_text(expected, encoding="utf-8")
        os.chmod(temporary, 0o644)
        temporary.replace(path)

    for path, expected in binary_outputs(tokens).items():
        if args.mode == "check":
            if not path.is_file() or path.read_bytes() != expected:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(f".{path.name}.new")
        temporary.write_bytes(expected)
        os.chmod(temporary, 0o644)
        temporary.replace(path)

    if stale:
        print("Stale appearance projections:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run ./scripts/generate-appearance.py build", file=sys.stderr)
        return 1
    if args.mode == "build":
        print("SenomyOS appearance projections updated.")
    else:
        print("SenomyOS appearance projections are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
