// Generated by scripts/generate-appearance.py. Do not edit directly.
.pragma library

var background = "#08090b";
var surface = "#0a0c0f";
var surfaceRaised = "#0f1115";
var foreground = "#f1f1f4";
var muted = "#92959f";
var dim = "#666a74";
var accent = "#9892e8";
var success = "#7fa98a";
var warning = "#c8a367";
var danger = "#c46f7d";
var fontFamily = "JetBrainsMono Nerd Font";
var radius = 5;
